#!/usr/bin/env bash
# Check if correct number of arguments is provided

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

# Assign values to variables
domain=$1
subdomain=$2

# Define the default subdomains to audit
subdomains=("www" "lb-01" "web-01" "web-02")

# If a specific subdomain is provided, use it
if [ -n "$subdomain" ]; then
    subdomains=("$subdomain")
fi

# Iterate through subdomains and display information
for sub in "${subdomains[@]}"; do
    result=$(dig +short "$sub.$domain")
    
    if [ -z "$result" ]; then
        echo "No DNS record found for $sub.$domain"
    else
        # Use awk to determine the record type (A or CNAME)
        record_type=$(dig +short "$sub.$domain" | awk 'NR==1{print length > 0 ? "A" : "CNAME"}')
        echo "The subdomain $sub is A $record_type record and points to $result"
    fi
done
