#!/usr/bin/env bash
# This script transfers a file from the client to the server using scp

# Check if the number of parameters is less than 4
if [ "$#" -lt 4 ]; then
    # Display the usage message and exit
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign the parameters to variables
FILE="$1"
IP="$2"
USER="$3"
KEY="$4"

# Use scp to transfer the file to the user home directory on the server
# Disable strict host key checking with -o option
scp -o StrictHostKeyChecking=no -i "$KEY" "$FILE" "$USER@$IP:~/"

# Exit with the status code of scp
exit $?
