#!/usr/bin/env bash
# Bash script to configure Nginx to return Hello World! at the root

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
