#!/usr/bin/env bash
# Script to install Nginx web server and configure redirection

# Update package list and install Nginx web server
sudo apt-get update
sudo apt-get install -y nginx

# Create Nginx configuration file for redirection
cat <<EOL | sudo tee /etc/nginx/sites-available/3-redirection
server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/@nkulumoncube5051;
    }
}
EOL

# Create a symbolic link to enable the new site
sudo ln -s /etc/nginx/sites-available/3-redirection /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

# Restart Nginx to apply changes
sudo service nginx restart

