#!/usr/bin/env bash
# Script to configure Nginx with a custom 404 page

# Install Nginx
apt-get update
apt-get install -y nginx

# Create Nginx configuration file for custom 404 page
cat <<EOL > /etc/nginx/sites-available/4-not_found_page_404
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root /var/www/html;
    index index.html index.htm;

    # Custom 404 error page
    error_page 404 /404.html;
    location = /404.html {
        return 404 "Ceci n'est pas une page.";
    }
}
EOL

# Create a symbolic link to enable the new site
ln -s /etc/nginx/sites-available/4-not_found_page_404 /etc/nginx/sites-enabled/

# Test Nginx configuration
nginx -t

# Restart Nginx to apply changes
service nginx restart

