#!/usr/bin/env bash
# Configures Nginx on a web server

# Install nginx
apt-get -y update
apt-get -y install nginx

# Add custom response header to know the server name for debugging
HOST_NAME=$(hostname)
HEADER="\\\n\tadd_header X-Served-By $HOST_NAME;\n"
CONFIG_FILE="/etc/nginx/sites-available/default"

# Check if the header already exists
FIND=$(grep "X-Served-By" "$CONFIG_FILE")
if [[ -z "$FIND" ]]; then
    # Find a server block and add the header inside it
    sed -i '/server {/a\'"$HEADER" "$CONFIG_FILE"
    echo "Custom header added to $CONFIG_FILE"
else
    echo "Custom header already exists in $CONFIG_FILE"
fi

# Create a first index.html page
echo "Hello World!" > /var/www/html/index.html

# Add to the nginx configuration file a redirection to another page
FIND=$(grep "redirect_me" "$CONFIG_FILE")
STRING="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=3MbaGJN2ioQ;\n\t}\n"
if [[ -z $FIND ]]; then
    sed -i "/server {/a\\$STRING" "$CONFIG_FILE"
fi

# Add to the nginx configuration file an error page 404
FIND=$(grep "error_page 404" "$CONFIG_FILE")
ERROR="\\\n\terror_page 404 /custom_404.html;\n"
if [[ -z $FIND ]]; then
    echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
    sed -i "/server {/a\\$ERROR" "$CONFIG_FILE"
fi

# Restart nginx service
service nginx restart
