#!/usr/bin/env bash
# Configures HAProxy on lb-01 server to distribute traffic to web-01 and web-02

# Install HAProxy on the server
apt-get -y update
apt-get -y install haproxy

# Configure HAProxy to distribute traffic using a round-robin algorithm
cat <<EOF > /etc/haproxy/haproxy.cfg
frontend krismaholdings.tech
    bind 0:8080
    default_backend web_servers

backend web_servers
    balance roundrobin
    server 234875-web-01 54.173.251.99:8080 check
    server 234875-web-02 52.91.125.177:8080 check
EOF

# Restart HAProxy service
service haproxy restart
