#!/usr/bin/env bash
# This script configures nginx to listen on port 80
sed -i 's/listen 80 default_server/listen 0.0.0.0:80 default_server/g' /etc/nginx/sites-available/default
service nginx restart

