#!/usr/bin/env bash

# This script displays the content of the file /etc/passwd.

while IFS=: read -r username _ userid _ _ homedir _ shell; do
    echo "The user $username is part of the $userid gang, lives in $homedir and rides $shell."
done < /etc/passwd
