#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user and listen on port 8080.

# Install sudo and change the Nginx user in the configuration
apt-get update
apt-get install -y sudo
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# Listen on all active IPs on port 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart

# Check Nginx status and port 8080 availability
ps auxff | grep ngin[x]
nc -z 0 8080
