#!/usr/bin/env bash

# Grant read, write, and execute permissions to specified files
chmod ugo+wrx /etc/apache2/ports.conf /etc/nginx/nginx.conf
sed -i -e 's/Listen 8080/#Listen 8080/g' -e 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill -1 apache2
sudo -u nginx service nginx restart
