#!/usr/bin/env bash
# Nginx configuration to run as the nginx user and listen on port 8080

sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
service nginx restart
ps auxff | grep 'nginx'
nc -z 0 8080
